### ISSUE TITLE
Thingy/Xreader dosen't save the page.

### ISSUE THREAD

**Issue by Watynecc** [linuxmint/thingy#10]
When I read "Learning Python 5th Edition" by Mark Lutz and close Xreader and then reopen with Thingy it just restart from the cover page.

I don't know how to get infomation of this bug because I don't see any error message in the terminal

**Comment by Watynecc** [comment]
Also from now It only does this with this book when I try with a other one it just work ? 😢

**Comment by adrianbiro** [comment]
@Watynecc 
If you have that book in .epub format, you can reformat it, which usually solves issues like that. Use the Calibre or Pandoc. The former is more straightforward.

**Comment by Watynecc** [comment]
All right! I will try

Le mer. 31 mai 2023, 16:31, Clement Lefebvre ***@***.***> a
écrit :

**Comment by Watynecc** [comment]
> Please reopen on xreader if you still experience the issue.

All right it work thanks you soo much !
