### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by SteveM2020** [linuxmint/thingy#11]
Not sure how this program got on Linuxmint, but then I thought it might be handy. Except there doesn't seem to be any way to use or add anything to it. If you can point me to a link where I can find out, that would be appreciated. If not, let me know there ins't any way to use it, and I'll remove it from my distribution and find something else.

**Comment by adrianbiro** [comment]
@SteveM2020 
You need to open some documents eg. a pdf with the appropriate application first, then when you close it, you can access that document via the Thingy.

**Comment by Moilleadoir** [comment]
I can only guess this has some Ubuntu dependencies because it does precisely nothing under Cinnamon on Manjaro.  It’d be good if there was some hint about what it required to work.

**Comment by clefebvre** [comment]
It shows favorites XApp favorites and Gtk recent files. Make sure your privacy settings allow for recent files to be recorded.
