### ISSUE TITLE
Adjusting right-click menu item - Move to trash.

### ISSUE THREAD

**Issue by adrianbiro** [linuxmint/thingy#14]
It's a minor thing, but it does not really move a document to the trash, but it removes it from the thingy overview of recently accessed documents. 

Every time I access this option it makes me think if I accidentally remove something that I shouldn't. 
It would be more appropriate to rename this item to something like **"Remove a shortcut from thingy/library"** or something in that spirit.

This adjustment is in the sphere of approaching users in a way that doesn't distract them from their workflow. 

Best wishes

**Comment by SoulRiets** [comment]
>  it does not really move a document to the trash
Actually It does. But I prefer to have two options: remove from Thingy and move to trash. It'd be great.

**Comment by adrianbiro** [comment]
You are right, it will remove a files not just remove thingy shortcut.  
I accidentally test it on files witch `chattr +i` flag and forgot on that.
And, yes, it woud by nice to have "remove from Thingy" shortcut.
