### ISSUE TITLE
How to install Thingy on other "Ubuntu" based distros?

### ISSUE THREAD

**Issue by shivanshsinghx365** [linuxmint/thingy#3]
Is there a way we can install thingy on other distros via deb packages or flatpak? if so, can you please guide us how to do so.

~Thank for you time and great project

**Comment by clefebvre** [comment]
Not through flatpak but it can compile as any deb package. The Debian packaging is included in the git repository.

**Comment by clefebvre** [comment]
https://linuxmint-developer-guide.readthedocs.io/en/latest/building.html#building-a-project-for-the-first-time
