### ISSUE TITLE
Program window is empty

### ISSUE THREAD

**Issue by Self-Layer** [linuxmint/thingy#8]
Thingy just shows an empty program window.

Even though I have opened .pdf and .odt documents they do not appear.

Also: There should be at least a short help text, that describes the purpose of the software & how to use it.

System report:
System:    Kernel: 5.4.0-96-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.16.0 
           tk: Gtk 3.24.20 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Hewlett-Packard product: Compaq Presario CQ61 Notebook PC v: Rev 1 
           serial: <filter> Chassis: Quanta type: 10 serial: <filter> 
           Mobo: Quanta model: 306A v: 21.0B serial: <filter> BIOS: Hewlett-Packard v: F.06 
           date: 06/03/2009 
CPU:       Topology: Dual Core model: Pentium T4200 bits: 64 type: MCP arch: Penryn rev: A 
           L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 7981 
           Speed: 1931 MHz min/max: 1200/2000 MHz Core speeds (MHz): 1: 1659 2: 1829 
Graphics:  Device-1: NVIDIA G98M [GeForce G 103M] vendor: Hewlett-Packard driver: nvidia 
           v: 340.108 bus ID: 01:00.0 chip ID: 10de:06ef 
           Display: x11 server: X.Org 1.20.13 driver: nvidia resolution: 1366x768~60Hz 
           OpenGL: renderer: GeForce G 103M/PCIe/SSE2 v: 3.3.0 NVIDIA 340.108 direct render: Yes 
Audio:     Device-1: Intel 82801I HD Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 chip ID: 8086:293e 
           Device-2: Logitech H600 [Wireless Headset] type: USB 
           driver: hid-generic,snd-usb-audio,usbhid bus ID: 4-2:2 chip ID: 046d:0a29 
           Sound Server: ALSA v: k5.4.0-96-generic 
Network:   Device-1: Qualcomm Atheros AR242x / AR542x Wireless Network Adapter 
           vendor: Hewlett-Packard driver: ath5k v: kernel port: 4000 bus ID: 02:00.0 
           chip ID: 168c:001c 
           IF: wlp2s0 state: up mac: <filter> 
           Device-2: Realtek RTL810xE PCI Express Fast Ethernet vendor: Hewlett-Packard 
           driver: r8169 v: kernel port: 2000 bus ID: 03:00.0 chip ID: 10ec:8136 
           IF: enp3s0 state: down mac: <filter> 
Drives:    Local Storage: total: 232.89 GiB used: 246.94 GiB (106.0%) 
           ID-1: /dev/sda vendor: Samsung model: HM251JI size: 232.89 GiB speed: 3.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 18.21 GiB used: 12.04 GiB (66.1%) fs: ext4 dev: /dev/sda5 
           ID-2: /home size: 43.88 GiB used: 38.66 GiB (88.1%) fs: ext4 dev: /dev/sda6 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 8 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 2-4:2 info: Quanta HP Webcam type: Video driver: uvcvideo rev: 2.0 
           chip ID: 0408:03f4 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Device-2: 4-2:2 info: Logitech H600 [Wireless Headset] type: Audio,HID 
           driver: hid-generic,snd-usb-audio,usbhid rev: 2.0 chip ID: 046d:0a29 
           Hub: 5-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 6-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 7-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 8-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
Sensors:   System Temperatures: cpu: 41.0 C mobo: N/A gpu: nvidia temp: 41 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb https: //mirror.init7.net/linuxmint una main upstream import backport
           2: deb http: //ubuntu.ethz.ch/ubuntu focal main restricted universe multiverse
           3: deb http: //ubuntu.ethz.ch/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //ubuntu.ethz.ch/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 194 Uptime: 3h 45m Memory: 3.81 GiB used: 2.46 GiB (64.6%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38

**Comment by clefebvre** [comment]
Make sure recent documents are enabled in your privacy settings. As you open them they'll start showing here.
